version: "3.9"
services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.9
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
  static:
    # image: "smtp_piccin_jorand/apache-php" # utilise une image déjà construite plutôt que d'en construire une nouvelle correspondant au Dockerfile
    build: ./ApachePHP
    ports:
      - "80"
      - "443"
    labels: 
      - "traefik.http.routers.static.rule=Host(`localhost`)"
  dynamic:
    # image: "http_piccin_jorand/express" # same as static
    build: ./Express
    ports:
      - "3000"
    labels: 
      - "traefik.http.routers.dynamic.rule=(Host(`localhost`) && PathPrefix(`/api`))"